name: ai_face_analyzer
description: "A Flutter plugin for on-device face detection using Google ML Kit with native Android and iOS implementations."
version: 1.0.0
homepage: https://github.com/vijayisonwork/ai_face_analyzer.git
repository: https://github.com/vijayisonwork/ai_face_analyzer.git
documentation: https://github.com/vijayisonwork/ai_face_analyzer.git
issue_tracker: https://github.com/vijayisonwork/ai_face_analyzer/issues

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.vs_plugin.ai_face_analyzer
        pluginClass: AiFaceAnalyzerPlugin
      ios:
        pluginClass: AiFaceAnalyzerPlugin